### ISSUE TITLE
DefinedBenefitPlanUltimateHealthCareCostTrendRate

### ISSUE THREAD

**Issue by deantp** [DataQualityCommittee/dqc_us_rules#47]
Unlikely to decline, but not impossible.

**Comment by campbellpryde** [comment]
Since 2012 only 4 values have been reported as negative and these filings used an incorrect element.  As such we will keep this element on the non negative list to detect the occurrence of an incorrect element. You are correct  it is theoretically possible to go negative, but that has not been actual experience.

**Comment by LMatherne** [comment]
Seems to me that rules should not be written to take into account market variables.  The rules should be based solely on the nature of the element.
